name: Run Install Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "CHANGELOG.md"
      - "MANIFEST.in"
      - "readme.md"
      - "scripts/**"
  workflow_dispatch:

jobs:
  plugin_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install test dependencies
        run: |
          pip install pytest pytest-timeout pytest-cov
      - name: Install ovos dependencies
        run: |
          pip install ovos-plugin-manager ovos-core[skills]~=0.0.2a11
      - name: Install package
        run: |
          pip install .
      - name: Run Plugin tests
        run: |
          pytest test/plugin_tests.py
